In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("customer_churn.csv")
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5485,7794-JASDG,Male,0,No,No,1,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.75,50.75,No
406,4742-DRORA,Male,0,Yes,Yes,60,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,One year,Yes,Bank transfer (automatic),95.40,5812,No
4716,5176-OLSKT,Female,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,No,No,No,Two year,No,Bank transfer (automatic),66.90,4370.25,No
2179,7311-MQJCH,Female,0,No,No,5,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Electronic check,19.55,99.6,No
4332,4194-FJARJ,Female,0,Yes,Yes,54,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),60.00,3273.95,No

In [3]:
df.drop('customerID',axis='columns',inplace=True)